### PR TITLE
Added a .addemote function

### PR DESCRIPTION
**Pull request by Ezeroth**
I kinda made a command that adds an emote, and it works too.

### CODE REVIEW

**Comment by shivaco** [comment]
[The last commit, though.](https://ci.appveyor.com/project/Kwoth/nadekobot/build/2.0.3765) 🤔

**Comment by shikhir-arora** [comment]
You'd also want to edit the command strings in https://github.com/Kwoth/NadekoBot/blob/1.9/src/NadekoBot/_strings/cmd/command_strings.json and add one following the format for your command, so it will have a help menu and register properly for things

**Comment by Kwoth** [comment]
Can you please squash your commits and revert credentials.json change?

**Comment by Ezeroth** [comment]
Uhhhh Kwoth, I tried asking you how to use Github, but you kinda blocked me. :think:

**Comment by Ezeroth** [comment]
I pressed the wrong button, ignore that please.

**Comment by shikhir-arora** [comment]
I don't mean to be mean, but this (a GitHub Pull Request) isn't the place you want to ask things like that. PR's should be ready to merge pending review.

You still need to add a command string: https://github.com/Kwoth/NadekoBot/blob/1.9/src/NadekoBot/_strings/cmd/command_strings.json for your command, otherwise doing `.help addemote` or whatever won't work. Any command that makes it to the bot needs to have this, or should.

And [there are many guides to GitHub like this one for squashing commits](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) and [this general site with some helpful stuff](https://ohshitgit.com). Google is your friend 🙂

**Comment by Ezeroth** [comment]
I'll make a new one once I've gotten a better understanding of GitHub

**Pull request closed without merging**
