### PR TITLE
Update LogCommand.cs

### PR DESCRIPTION
**Pull request by fkndean**
Lets actually make the log have a proper date format.

### CODE REVIEW

**Comment by samdivaio** [comment]
logserver uses default server time so I don't think it is necessary to add the whole long data and time format and with UTC

**Comment by Kwoth** [comment]
just change it from .Now to .UtcNow

**Comment by fkndean** [comment]
Honestly personal preference 📦

**Comment by samdivaio** [comment]
If its possible to include choosing time zone/server(guild) that would be useful even with date option to choose from that would be best.

**Pull request closed without merging**
