### PR TITLE
NadekoBot is translated to Turkish

### PR DESCRIPTION
**Pull request by DaYWhiTe**
There is now a translation.

Status: %100

Thank You ♥️
🎉 -Mehmet Doğan 🎉

### CODE REVIEW

**Comment by DaYWhiTe** [comment]
I opened it 2 times I am sorry

**Comment by DaYWhiTe** [comment]
I can't translate utility_activity_line.

i need sample

**Comment by Kwoth** [comment]
What's your discord username#discrim?

**Comment by DaYWhiTe** [comment]
DaYWhiTe#4683

**Pull request merged**
