### PR TITLE
Recreated #1513

### PR DESCRIPTION
**Pull request by halitalf**
Recreation of Pull Request #1513 

I reverted to upstream, restored my changes, and implemented the required changes stated in #1513.

### CODE REVIEW

**Comment by halitalf** [comment]
What happened here?

**Comment by Kwoth** [comment]
I will merge it, just need more time to test and push xp and club features.

**Comment by halitalf** [comment]
OK. I just had begun to think it got forgotten about with it being almost a month old. Anyway, thanks for the update @Kwoth

**Comment by Kwoth** [comment]
Can you get this ready for merge please?

**Comment by halitalf** [comment]
What do I need to do to get it ready for merge?

**Comment by Kwoth** [comment]
merge my 1.4 into yours, then push

**Comment by halitalf** [comment]
Pulled changes. Ready for merge.

**Comment by halitalf** [comment]
Well I thought it was, I pulled the changes again and fixed the merge conflicts. Should be ready now.

**Comment by halitalf** [comment]
this just got real complicated... it was working until your latest commits. Not sure what got borked. I'm just gonna rewrite the changes to NSFW.cs from scratch.

**Comment by halitalf** [comment]
There we go. Got it fixed.

**Comment by Macley-Kun** [comment]
@Kwoth bump~

**Comment by Kwoth** [comment]
Hey i coped manually these changes to 1.9 branch because of merge conflicts. When 1.9 is ready for public use. I've left a comment saying you implemented them :^) 

Thanks for the help

**Comment by halitalf** [comment]
Happy to help @Kwoth! Just to confirm, these features will not be available in the 1.4 branch?

**Comment by Kwoth** [comment]
Nope

**Pull request closed without merging**
