### PR TITLE
Fixed youtube time argument

### PR DESCRIPTION
**Pull request by Seregy**
Fixed time argument in youtube links(#363), now it should properly handle hours and minutes

### CODE REVIEW

**Comment by Nitix** [comment]
https://youtu.be/xxxxxxx?t=111 is also a correct time argument, and I'm not sure that your new regex can handle it.

**Comment by Kwoth** [comment]
^ exactly my thoughts. youtu.be link have h/m/s thing. Normal youtube links with time have just a number in seconds

**Comment by Seregy** [comment]
That should fix it

**Comment by Kwoth** [comment]
looks correct, ill clone the PR tomorrow localy to test it and I'll accept if it works properly, thanks a lot

**Comment by Kwoth** [comment]
Works, and i like how you did it. ^^ thanks a lot

**Pull request merged**
