### PR TITLE
Adds .rolehoist command

### PR DESCRIPTION
**Pull request by snipplets**

### CODE REVIEW

**Comment by Kwoth** [comment]
What is hoist?

**Comment by snipplets** [comment]
It's terribly named imo, but it's toggling if the role is displayed on the sidebar with the other online users
https://discordapp.com/developers/docs/resources/guild#modify-guild-role

**Comment by snipplets** [comment]
checkbox
Allows you to set that check box for a given role basically.

**Comment by snipplets** [comment]
Do you want me to grab localized translations for the response or do you have a script to do it?

**Comment by Kwoth** [comment]
Just add the default one to ResponseStrings.resx

**Comment by Kwoth** [comment]
clean 👌

**Comment by DogeOps97** [comment]
`.roledisplay` can be good? lol 🤔

**Pull request merged**
