### PR TITLE
Allow for optional "titleurl" field for embed title [clickable]

### PR DESCRIPTION
**Pull request by shikhir-arora**
This allows the title to be clickable from a long-standing iOS bug.

It is optional, but when inputted the `"url": "http://something.com"` will act as it should and make that field clickable. 

`{ "title":"Something", "url":"https://google.com" }` (with URL for the title)
`{ "title":"Something" }` (without URL, as normal) 

Have tested and confirmed working. Pictures are on the commit below.

### CODE REVIEW

**Comment by Kwoth** [comment]
The field has to be called just `url`, in order to be inline with api and discord.net model.

**Comment by shikhir-arora** [comment]
Changed to `url`

**Comment by Kwoth** [comment]
You also have to check whether the URL is valid, see how thumbnail and image are done.

**Comment by shikhir-arora** [comment]
Should be good to go.

**Comment by Kwoth** [comment]
ty

**Pull request merged**
