### PR TITLE
Don't exclude bots from the party.

### PR DESCRIPTION
**Pull request by nickhudkins**
Hardcoding the ignoring of bots is obnoxious. Treat them like users, ban them if they misbehave, don't grant them permissions that you don't want a person having.

### CODE REVIEW

**Comment by samdivaio** [comment]
b1nzy gonna be super proud 😄

**Comment by nickhudkins** [comment]
@Kwoth closed because....? There is an entirely valid use case here. If you'd like I can make it configurable instead, but this seems like one of the more silly checks to have.

**Comment by Kwoth** [comment]
Closed because no, nadeko will not receive commands from other bots.

**Comment by nickhudkins** [comment]
Sure it does, just run my fork @Kwoth.

**Pull request closed without merging**
