### PR TITLE
Add Minecraft Searches

### PR DESCRIPTION
**Pull request by fkndean**

### CODE REVIEW

**Comment by Kwoth** [comment]
Woah! Awesome.

**Comment by Kwoth** [comment]
Can you please remove mcuser, it's really useless, and make ~mcquery alias shorter, maybe ~mcq. Error responses should be wrapped in "`" and drop the [MINECRAFT] from the message.

**Comment by fkndean** [comment]
ok i will.
was just messing about. will clean it up.

**Comment by Kwoth** [comment]
I completely forgot about this PR, why was it closed?

**Comment by fkndean** [comment]
ill make a new PR later :p. didnt have a lot of time recently sorry.

---- On Fri, 04 Nov 2016 14:42:14 -0700 notifications@github.com wrote ----

I completely forgot about this PR, why was it closed?

**Pull request closed without merging**
