### PR TITLE
Grammar pls

### PR DESCRIPTION
**Pull request by FrostTheFox**
was fooled on last PR, set the wrong branch >.>

Minor text fixes.

### CODE REVIEW

**Comment by fkndean** [comment]
If I could give you a eggplant with sweat, I would.

**Comment by FrostTheFox** [comment]
wew

**Comment by Nitix** [comment]
To be honest, your commit merged without conflict, you could still use the previous PR. Also the branch's name doesn't impact the merge.

**Comment by FrostTheFox** [comment]
¯\_(ツ)_/¯

**Pull request merged**
