### PR TITLE
Updated 0.9 Guide to make it work for it's EOL

### PR DESCRIPTION
**Pull request by ShotzPotz**
Updated the Windows guide to just download the last release and made a huge banner on the index to explain no more official support.

### CODE REVIEW

**Comment by Kwoth** [comment]
likeALLL checks haf fiald
image its not even hallf

**Comment by ShotzPotz** [comment]
how tf does it check if a guide works?

**Comment by samdivaio** [comment]
xD you pr'ed it to dev branch, it should go to 0.9 branch

**Comment by ShotzPotz** [comment]
oh bugger did i? sorry lol thought I did it to the 0.9 one

**Comment by ShotzPotz** [comment]
changed it to 0.9, whoops

**Comment by samdivaio** [comment]
Nope you pr'ed it from Kwoth's dev to Kwoth's 0.9 branch

**Comment by samdivaio** [comment]
Oh wait a sec something else is wrong, you fixed it I read it wrong

**Comment by ShotzPotz** [comment]
:)

**Pull request closed without merging**
