### PR TITLE
Initial BNET API support.

### PR DESCRIPTION
**Pull request by fkndean**
If people want it ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by samdivaio** [comment]
I do. ¯_(ツ)_/¯

**Comment by fkndean** [comment]
This gui

**Comment by fkndean** [comment]
Fixed the issue regarding wrong class and race showing up with this latest commit.

**Comment by Kwoth** [comment]
you should make region an enum

**Comment by fkndean** [comment]
Will do in a future commit I intend to do.

**Comment by thyica** [comment]
+1 that would come handy in my gaming discord

**Comment by fkndean** [comment]
Going to be working on adding in Overwatch later.

**Pull request closed without merging**
