### PR TITLE
Fixed Unhandled Exceptions Crashing NadekoBot.

### PR DESCRIPTION
**Pull request by AraHaan**
Whenever a Exception happens while trying to Login NadekoBot Crashes. With this it prevents a crash and tells you the exception message.

### CODE REVIEW

**Comment by Nitix** [comment]
Not sure but having the the name of the exception and the stack trace in the console, may help to troubleshoot the crash.

**Comment by AraHaan** [comment]
hmm true.

**Comment by Kwoth** [comment]
it already prints errors in the console, so no need for this, also, don't use console.writeline but Logging

**Comment by AraHaan** [comment]
Actually even then your exception handling is not handled at the time these exceptions are thrown so then mine catches it otherwise Nadekobot will actually crash with them unhandled because of a few core issues that can happen so, this wors, I could use your logger though. But yeah any Exception it has while and before it can login (which can happen) can actually come unhandled because of this:

    internal Task LoginAsync(TokenType tokenType, string token) =>
        Task.WhenAll(Clients.Select(async c => { await c.LoginAsync(tokenType, token); _log.Info($"Shard #{c.ShardId} logged in."); }));

can actually fail. As well as anything Else like if discord.net fails to create a websocket that it would Crash Nadeko as well. So making it not crash unhandled is a must.

**Comment by AraHaan** [comment]
Well Edited Wrong file now that I look in NadekoBot.cs that is the file I should have edited for this.

**Pull request closed without merging**
