### PR TITLE
Changes to guides

### PR DESCRIPTION
**Pull request by DogeOps97**
Editing Linux (Deleted most of the manual installation part), OSX, and Windows (gifs) guide

### CODE REVIEW

**Comment by Kwoth** [comment]
@samdivaio can you see if this is fine?

**Comment by samdivaio** [comment]
Changes to linux guide should be:
- Switch the manual installation link to <https://github.com/Kwoth/NadekoBot-BashScript/blob/master/nadekoautoinstaller.sh>
- Setting up credentials.json (manually) and Setting up SFTP step shouldn't removed.
- All heads should have a space between `#` and `text` (Optional) github changed markdown for hashtags.

**Comment by DogeOps97** [comment]
Well, I guess that's about it

**Comment by DogeOps97** [comment]
@samdivaio o.o)7

**Comment by Kwoth** [comment]
thx dogo

**Pull request merged**
