### PR TITLE
Moved PokemonTypes to their own json

### PR DESCRIPTION
**Pull request by appelemac**

### CODE REVIEW

**Comment by Kwoth** [comment]
all pokemon types need to be moved to json, not just moves. 

You would have a type with multipliers array/object, name, icon, and moves array

**Comment by tg44** [comment]
Please don't take things to the bin folder. Take it to a resources folder, and in the properties window choose the copy option. It's a bad thing that the whole bin folder is not in the gitignore!
(If I will have time, I will do it to the other stuffs too.)

**Comment by appelemac** [comment]
@tg44 idk what Kwoth intends to do with it, so I'll leave it all together for now

**Comment by Kwoth** [comment]
Thx, we'll leave the moving stuff to resources to tg44 if he wants to do it.

Maybe its better to have multipliers as a matrix?

**Pull request merged**
