### PR TITLE
Add BF3/BF4 API Searches (Online Players and User Search)

### PR DESCRIPTION
**Pull request by fkndean**
Initial Commit.

### CODE REVIEW

**Comment by Kwoth** [comment]
Don't use stringbuilder if you don't have a loop. Use multiline strings, check the edit i made on your wikia search. Also don't show irrelevant info. It would be also nice to provide screenshot(s) on how it works since there is a lot of code.

**Comment by fkndean** [comment]
alright, will do

---- On Sat, 12 Nov 2016 11:16:59 -0800 notifications@github.com wrote ----

Don't use stringbuilder if you don't have a loop. Use multiline strings, check the edit i made on your wikia search. Also don't show irrelevant info. It would be also nice to provide screenshot(s) on how it works since there is a lot of code.

**Comment by fkndean** [comment]
I will be able to do it later tonight. Got exams :3

---- On Sat, 12 Nov 2016 11:16:59 -0800 notifications@github.com wrote ----

Don't use stringbuilder if you don't have a loop. Use multiline strings, check the edit i made on your wikia search. Also don't show irrelevant info. It would be also nice to provide screenshot(s) on how it works since there is a lot of code.

**Comment by fkndean** [comment]
Takes arguments like this for when searching for user
`~bfu <platform> <game (bf3/bf4)> <username>`

image
image
image

**Comment by Kwoth** [comment]
Looks very nice, thanks

**Pull request merged**
