### PR TITLE
ResponseStrings.uk-UA.json

### PR DESCRIPTION
**Pull request by AndriyMeleshko**
Translation from English to Ukrainian document ResponseStrings.en-US.json
Country: Ukraine
Language: Ukrainian

### CODE REVIEW

**Comment by shivaco** [comment]
Do you have access to NadekoBot strings on POEditor?

**Comment by AndriyMeleshko** [comment]
no

**Comment by AndriyMeleshko** [comment]
I'm sorry I can not use POEditor

**Comment by AndriyMeleshko** [comment]
How to access NadekoBot strings on POEditor?

**Comment by shivaco** [comment]
Join [this server](https://discord.gg/nadekobot] and send a DM to Kwoth#2560, he will send you instructions.

**Comment by AndriyMeleshko** [comment]
Thank you

**Pull request closed without merging**
