### PR TITLE
Fix the heck out of LeetCommand.

### PR DESCRIPTION
**Pull request by FurkanKambay**
I haven't seen anything like those switch cases in my life.
I tested with a few words, exact matches.

### CODE REVIEW

**Comment by FurkanKambay** [comment]
List of changes (Line numbers are for the new file):
(because the Diff looks so weird.)

- L18: There was an inconsistency between the other Games. So I created a class by properly with the attribute and base class.
- L23, L45: Little improvements.
- L43-75: Removed the switch-cases. Instead used a lookup strategy. The rest should be easy.
- L78: New lookup table.

**Comment by Kwoth** [comment]
Woah, I forgot we had that there. It indeed is disgusting. Thanks so much. Just remove the top comment now as you rewrote it completely?

**Comment by FurkanKambay** [comment]
No problemo!

**Comment by Kwoth** [comment]
Lovely. Thanks a lot. Would love to see more of PRs like these haha.

**Pull request merged**
