### PR TITLE
Add Yande.re search

### PR DESCRIPTION
**Pull request by fkndean**

### CODE REVIEW

**Comment by Kwoth** [comment]
Hey, thanks for another pr!

If they do have an api, since i see you're using .xml, maybe use it normally instead of regex. and if you could check if there is 2 tag limit on this one too for sure. If tag limit is greater than 2, then use one for Order:random, and get only first post - much less expensive. 1000 is too much. Also add it to ~hentaibomb.

**Comment by fkndean** [comment]
Doing it now and looking further into it, I found that it's pretty much the same as danbooru. I don't use these sites lol. Going to be pushing commits soon.

**Comment by fkndean** [comment]
image

**Comment by fkndean** [comment]
Removed safeyandere due to request.

**Comment by Kwoth** [comment]
ty 👌

**Pull request merged**
