### PR TITLE
Too many people forgetting it

### PR DESCRIPTION
**Pull request by MaybeGoogle**
Comma in credentials

### CODE REVIEW

**Comment by coconut24** [comment]
instersting... cant you tell people to add these two lines before the end bracket and put a comma before the first line instead? json would be able to parse that normally

**Comment by shikhir-arora** [comment]
I think the comma issue was addressed in https://github.com/Kwoth/NadekoBot/pull/1870

**Comment by MaybeGoogle** [comment]
@shikhir-arora no, that looks like a different line.
@coconut24 or even better, put those two right after the open bracket and add a comma on the second line. That way formatting is maintained. thanks!

**Comment by Kwoth** [comment]
Thanks

**Pull request merged**
