### PR TITLE
Reworked Questions.

### PR DESCRIPTION
**Pull request by Bakaba**
Syntax need to be the same in every questions. (Spaces, punctuation, uppercase, etc.)
Category are for now : Anime, Arts, Biology, Games, Geography, History, Literatures, Movies, Musics, Other, Riffles, Science, Sports.
Remaining questions is updated on my fork, but not merged.

### CODE REVIEW

**Comment by appelemac** [comment]
Oh nice~

**Comment by appelemac** [comment]
The comma after the last item should be removed

**Comment by appelemac** [comment]
In left_questions.json, you forgot a lot of commas after the category: 
```
{
    "Category": "Biology"
    "Question": "What wreath of flowers is used as a decoration?",
    "Answer": "Garland"
},
```
->
```
{
    "Category": "Biology",
    "Question": "What wreath of flowers is used as a decoration?",
    "Answer": "Garland"
},
```

**Comment by Kwoth** [comment]
Sounds good, the question is, will it parse? :D 

I'll check it out tonight

**Comment by Bakaba** [comment]
Oh, yes, my bad x) I did reorganize questions, and forgot to remove the last coma.
The "left_question.json" is not "ready to use", so it missing lot of thing. (In true, i didn't want to merge it, but, since I'm new in Github, I think I've done something wrong...)
I'll focus on my studies, so I'll not work on questions until my exams are done.
I apologize for this inconvenience.

**Comment by Kwoth** [comment]
@Bakaba how much of the original questions are converted?

**Comment by Bakaba** [comment]
Hm, approximately 700 questions.

**Comment by Kwoth** [comment]
Out of?

**Comment by Bakaba** [comment]
~5000...

**Comment by Kwoth** [comment]
PR dev branch from now on

**Pull request closed without merging**
