### PR TITLE
whitelist catblaster from slowmode

### PR DESCRIPTION
**Pull request by Ckath**
please whitelist me from this hell

### CODE REVIEW

**Comment by Ebolo** [comment]
https://ebolo.s-ul.eu/3UqaoPIn

**Comment by appelemac** [comment]
Doesn't this just prevent you from being ratelimited

**Comment by appelemac** [comment]
@Kwoth It should be acceptable if we change it to those with Manage Messages perms for the channel

**Comment by Ckath** [comment]
that's the point

**Comment by Kwoth** [comment]
XD

**Pull request closed without merging**
