### PR TITLE
fix crca wont work on chinese sentences

### PR DESCRIPTION
**Pull request by coconut24**
getwordposition should ignore special characters, but still look for valid word chars(A-Z, a-z)
should i make it look for characters below =<255? (eg. "@{}()" and such) :thinking:

### CODE REVIEW

**Comment by Macley-Kun** [comment]
Thanks for making this pull to fix our issue we had for about 3 months!
Idk if its possible to have a look at This issue: #1366. Its Kinda simalir But perhapes u can make a pull for this one too. Still thanks again for making this pull :33

**Comment by Kwoth** [comment]
Thanks a lot, but yeah, some special characters which are used often, like @ and #, etc could make a problem, if you had a crca with them. Not sure who would put them as CRCA expecting the sentence to contain a word "?", i think it's fine like this?

**Comment by Kwoth** [comment]
#1817

**Comment by coconut24** [comment]
another way to fix this is detecting cjk characters, but korean does use spaces. and theres many languages that doesnt use space as word divider or word divider at all.
it would be unnecessary to list all languages without/with different word dividers

**Comment by Kwoth** [comment]
Thanks for the help

**Pull request merged**
