### PR TITLE
Update SearchHelper.cs

### PR DESCRIPTION
**Pull request by Iratu**
Fixed danbooru to use a bit more of the build in system to randomly select an image, might work faster if "&limit=1" is added to the image search link but haven't tried this yet.

### CODE REVIEW

**Comment by ShadowNoire** [comment]
ive got a further upgrade that replaces sample images with the full size versions

**Comment by Iratu** [comment]
To get full sized images all you need to change is

`var matches = Regex.Matches(webpage, "data-large-file-url=\"(?<id>.*?)\"");`

to

`var matches = Regex.Matches(webpage, "data-file-url=\"(?<id>.*?)\"");`

**Comment by Kwoth** [comment]
won't this reduce the number of allowed tags from 2 to 1?

**Comment by Iratu** [comment]
Hmm, I forgot about that limit, mainly because I upped it to 5 on the booru I run but yes it will reduce it to one, I think it would be nice to add support for the API login so people can increase the search limit to 6 or 12 depending if they have gold or platinum.

**Pull request closed without merging**
