### PR TITLE
Update

### PR DESCRIPTION
**Pull request by samdivaio**
- Added rich embed to help and changed a few things. Thanks to fkndean https://github.com/Kwoth/NadekoBot/pull/819
- clickin on Help links to list of commands
- Added emojis to stream notifications.
- Changed weather colour Nadeko.OK to colour of sunlight.
- stats colour changed to colour of info.
- lowed the contrast of nadeko ok and nadeko error embed colour

### CODE REVIEW

**Comment by Kwoth** [comment]
please revert weather to green, remove the 2 extra properties you added, leave info blue but just write that color normally, not as a poperty on NadekoBot.
-h command needs more work, i don't like that info emoji, i don't think there should be emoji at all, just needs to be formatted better

**Comment by samdivaio** [comment]
👌 I'm on it

**Comment by samdivaio** [comment]
Done xD

**Comment by Kwoth** [comment]
merge conflict, you changed streamnotifications too

**Comment by samdivaio** [comment]
wait!!! found a bug with embeds on help commands

**Comment by samdivaio** [comment]
redoing stream

**Pull request closed without merging**
