### PR TITLE
.dtch fix

### PR DESCRIPTION
**Pull request by fkndean**

### CODE REVIEW

**Comment by samdivaio** [comment]
Tested ✅
Working ✅

**Comment by Kwoth** [comment]
?! what's the difference between this and my fix?

**Comment by fkndean** [comment]
¯\_(ツ)_/¯

**Comment by samdivaio** [comment]
lol Kevin you dont know? xD
Kwoth you fix make the bot reply the channel name and ID of the channel where the command is used. And that fix fixes that and makes the bot reply the channel name and ID of the deleted text channel.

**Comment by Kwoth** [comment]
that doesn't sound right

**Comment by samdivaio** [comment]
it was weird thing to see but now its working like magic.
kwoth your fix is working perfectly,
I don't know what happened back then, :/

**Pull request closed without merging**
