### PR TITLE
Pokemon revamp

### PR DESCRIPTION
**Pull request by appelemac**

### CODE REVIEW

**Comment by appelemac** [comment]
BJOOM BIATCH

**Comment by ShadowNoire** [comment]
i just added chances for crit and miss to mine. /flipstable so much for that lel

**Comment by Kwoth** [comment]
When you do the property/method name refactor, also please remove all of the extra empty liines, there is so many of them.

**Comment by ShadowNoire** [comment]
seems to be really buggy, but a ton of fun. i'll let you know what i find and fix @appelemac

**Comment by Kwoth** [comment]
unneeded ;p

**Pull request closed without merging**
